DROP TABLE IF EXISTS menu_items CASCADE;

CREATE TABLE menu_items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(6, 2) NOT NULL,
  description TEXT NOT NULL,
  thumbnail_photo_url VARCHAR(255) NOT NULL,
  prep_time INTEGER NOT NULL DEFAULT 15
);
